name: Exec Test

on:
  workflow_dispatch:

jobs:
  master_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          ./build/linux-x64/MasterChecker